default_rel_patches = {
    "perfect-bonus-completion": False,
    "remove-desert-haze": False,
    "story-mode-music-fix": False,
    "no-music-vol-decrease-on-pause": False,
    "story-mode-char-select": False,
    "no-hurry-up-music": False,
    "fix-revolution-slot": False,
    "fix-labyrinth-camera": False,
    "challenge-mode-death-count": False,
    "disable-how-to-play-screen": False,
    "fix-wormhole-surfaces": False,
    "fix-stage-object-reflection": False,
    "enhance-reflective-surfaces": False,
    "custom-music-id": False,
    "custom-theme-id": False,
    "skip-intro-movie": False,
    "smb1-camera-toggle": False,
    "fix-missing-w": False,
    "skip-cutscenes": False,
    "remove-playpoints": False,
    "fix-storm-continue-platform": False,
    "fix-any-percent-crash": False,
    "party-game-toggle": False,
    "enable-menu-reflections": False,
    "custom-world-count": 10,
    "stobj-draw-fix": False
}
